package armorpaint

type Config struct {
	Locale              string   `json:"locale"`
	WindowMode          int      `json:"window_mode"`
	WindowW             int      `json:"window_w"`
	WindowH             int      `json:"window_h"`
	WindowX             int      `json:"window_x"`
	WindowY             int      `json:"window_y"`
	WindowResizable     bool     `json:"window_resizable"`
	WindowMaximizable   bool     `json:"window_maximizable"`
	WindowMinimizable   bool     `json:"window_minimizable"`
	WindowVsync         bool     `json:"window_vsync"`
	WindowFrequency     int      `json:"window_frequency"`
	WindowScale         int      `json:"window_scale"`
	RpSupersample       int      `json:"rp_supersample"`
	RpSsao              bool     `json:"rp_ssao"`
	RpSsr               bool     `json:"rp_ssr"`
	RpBloom             bool     `json:"rp_bloom"`
	RpMotionBlur        bool     `json:"rp_motionblur"`
	RpGi                bool     `json:"rp_gi"`
	RpVignette          float64  `json:"rp_vignette"`
	RpGrain             float64  `json:"rp_grain"`
	Version             string   `json:"version"`
	Sha                 string   `json:"sha"`
	RecentProjects      []string `json:"recent_projects"`
	Bookmarks           []string `json:"bookmarks"`
	Plugins             []string `json:"plugins"`
	Keymap              string   `json:"keymap"`
	Theme               string   `json:"theme"`
	UndoSteps           int      `json:"undo_steps"`
	CameraPanSpeed      int      `json:"camera_pan_speed"`
	CameraZoomSpeed     int      `json:"camera_zoom_speed"`
	CameraRotationSpeed int      `json:"camera_rotation_speed"`
	ZoomDirection       int      `json:"zoom_direction"`
	WrapMouse           bool     `json:"wrap_mouse"`
	ShowAssetNames      bool     `json:"show_asset_names"`
	TouchUI             bool     `json:"touch_ui"`
	SplashScreen        bool     `json:"splash_screen"`
	Layout              []int    `json:"layout"`
	LayoutTabs          []int    `json:"layout_tabs"`
	Workspace           int      `json:"workspace"`
	CameraControls      int      `json:"camera_controls"`
	Server              string   `json:"server"`
	PressureRadius      bool     `json:"pressure_radius"`
	PressureSensitivity int      `json:"pressure_sensitivity"`
	DisplaceStrength    int      `json:"displace_strength"`
	LayerRes            int      `json:"layer_res"`
	BrushLive           bool     `json:"brush_live"`
	Brush3D             bool     `json:"brush_3d"`
	NodePreview         bool     `json:"node_preview"`
	PressureHardness    bool     `json:"pressure_hardness"`
	PressureAngle       bool     `json:"pressure_angle"`
	PressureOpacity     bool     `json:"pressure_opacity"`
	MaterialLive        bool     `json:"material_live"`
	BrushDepthReject    bool     `json:"brush_depth_reject"`
	BrushAngleReject    bool     `json:"brush_angle_reject"`
	Dilate              int      `json:"dilate"`
	DilateRadius        int      `json:"dilate_radius"`
}
