name: Go

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Fetch go mods
        working-directory: ./
        run: go mod tidy

      - name: Build
        working-directory: ./
        run: go build -o main cmd/apccm/main.go

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist
          path: |
            ./main